[package]
name = "ropes_sim"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ggez = "0.7"
glam = "0.21"
enum-map = "2.4"
slab = "0.4"
rand = "0.8"